spring:
  profiles:
    include: bootstrap

  datasource:
    url: jdbc:mysql://localhost:3306/sample?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 8244
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 5000
      minimum-idle: 10
      maximum-pool-size: 100
      jdbc-url: jdbc:mysql://localhost:3306/sample?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

logging:
  level:
    org.hibernate.sql: info
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true

vault:
  uri: http://localhost:8200
  token: admin
  app-role:
    role-id: e50a9f5c-55d6-6376-cb74-1f9629e6561a
    secret-id: 2753984d-9719-9b91-4b46-b0cc3d4629b2
  secret:
    appconfig: teople/local

mysql:
  url: jdbc:mysql://localhost:3306/sample?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  username: root
  password: 8244