spring:
  profiles:
    include: bootstrap

  datasource:
    hikari:
      connection-timeout: 5000
      minimum-idle: 10
      maximum-pool-size: 100

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true

vault:
  uri: http://localhost:8200
  token: admin
  app-role:
    role-id: e50a9f5c-55d6-6376-cb74-1f9629e6561a
    secret-id: 2753984d-9719-9b91-4b46-b0cc3d4629b2
  secret:
    appconfig: teople/local

